export const ITEMS_LIST_REQUEST = 'ITEMS_LIST_REQUEST';
export const ITEMS_LIST_SUCCESS= 'ITEMS_LIST_SUCCESS';
export const ITEMS_LIST_FAIL = 'ITEMS_LIST_FAIL';

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST';

export const ITEMS_LIST_INSTANT_FILTER_REQUEST = 'ITEMS_LIST_INSTANT_FILTER_REQUEST';
export const ITEMS_LIST_INSTANT_FILTER_SUCCESS = 'ITEMS_LIST_INSTANT_FILTER_SUCCESS';

